version: 2.1
executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: |
            ls -al
            pwd
            dotnet restore
      - run:
          name: Build
          command: |
            dotnet build --no-restore
            ls -al
            echo "export IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $BASH_ENV
            echo $BASH_ENV
            echo "Rashmika Manawadu"
      - run:
          name: Build and push docker image
          command: |
            source $BASH_ENV
            echo $IMAGE_TAG

